#!/bin/sh

mkdir -p vendor

# using jekyll docker image: https://github.com/envygeeks/jekyll-docker
export JEKYLL_VERSION=3.8
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  --volume="$PWD/vendor:/usr/local/bundle" \
  --publish 4000:4000 \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  $*